### ISSUE TITLE
Challenge 6: Require "New nº of signatures required" >0 when adding or removing signers

### ISSUE THREAD

**Issue by Pabl0cks** [scaffold-eth/se-2-challenges#123]
At the moment it lets you create proposals with "New Nº" empty or 0. When you try to exec the transaction at the Pool, it throws a transaction error.

**Comment by Deepak2030** [comment]
Hello, can you describe the issue in detail?

**Comment by d0ra-1h3-3xpl0ra** [comment]
Are there any updates, @Pabl0cks? I can help.

**Comment by Pabl0cks** [comment]
Sorry @Deepak2030 and @d0ra-1h3-3xpl0ra I missed the first ping!

I've captured a video of the use case, but now I feel that is a bit too edge case, and since it's not a consumer product we probably should not even bother controlling the error to be more specific in the notification. I'll close this for now, thanks anyways for your help offering ♥🙌

Video => https://www.loom.com/share/799d5b3bda0a40afa6c67c897c8be923?sid=b471d0fc-cb02-4b09-a267-602e8724da80
