### ISSUE TITLE
Update tests to supplement autograder

### ISSUE THREAD

**Issue by technophile-04** [scaffold-eth/se-2-challenges#138]
### Description : 

We need to remove `ethers.getContractAt`  approach and use `ethers.getContractFactory` also add `let contractArtifact` variable : 

Checkout https://github.com/scaffold-eth/se-2-challenges/pull/137/files for reference 

TODO: 
- [x] Base template 
- [x] Update #136 (chall 0)
- [x] Chall 1 (#139)
- [x] Chall 2 (#140)
- [x] Chall 3
- [x] Chall 4
- [x] Chall 5

**Comment by carletex** [comment]
>  ✅ Update https://github.com/scaffold-eth/se-2-challenges/pull/136 (chall 0)

Pushed https://github.com/scaffold-eth/se-2-challenges/pull/136/commits/efe6e44f2d49be996f36226b9c6a703a31a14f4f to #136

**Comment by carletex** [comment]
Cha1: #139 
Cha2: #140 

Will continue later (or Monday) but any of you feel free to keep going!

**Comment by carletex** [comment]
Thanks @technophile-04 for tackling the remaining challenges.

Should we tweak this from the base template before closing this issue? https://github.com/scaffold-eth/se-2-challenges/tree/base-challenge-template/packages/hardhat/test

**Comment by rin-st** [comment]
hey, created pr for update of base-challenge-template test https://github.com/scaffold-eth/se-2-challenges/pull/156

**Comment by rin-st** [comment]
as I understand we can close this?
