### ISSUE TITLE
Install package too low

### ISSUE THREAD

**Issue by yucheng-Li** [scaffold-eth/se-2-challenges#144]
<img width="939" alt="WX20240302-123946@2x" src="https://github.com/scaffold-eth/se-2-challenges/assets/61103353/1f0c929c-07ee-43e5-8b04-b07f23637925">

It my network problem ?

**Comment by rin-st** [comment]
It seems yes. Do you have that problem with other projects?

**Comment by yucheng-Li** [comment]
已收到
