### ISSUE TITLE
Backmerge vercel deployment fix

### ISSUE THREAD

**Issue by technophile-04** [scaffold-eth/se-2-challenges#157]
### Description : 

We recently merge https://github.com/scaffold-eth/scaffold-eth-2/pull/757, let backmerge it  in all challenges also remove #91 from challenge 0

**Comment by technophile-04** [comment]
We should merge https://github.com/scaffold-eth/scaffold-eth-2/pull/780 instead

**Comment by rin-st** [comment]
Completed!
