### ISSUE TITLE
Implement Challenge 3 : 🎲 Dice Game

### ISSUE THREAD

**Issue by Ifechukwudaniel** [scaffold-eth/se-2-challenges#18]
TODO :

- [x]  Contracts 
- [x]  UI 
- [ ] Readme 
- [x] Tests

**Comment by Ifechukwudaniel** [comment]
@carletex should I get with this  or is there someone working on it already

**Comment by carletex** [comment]
hey @Ifechukwudaniel thanks for creating the issues!!

I think @rin-st is working on some of them, let's see what he says.

**Comment by rin-st** [comment]
I'm working on Challenge 2

**Comment by Ifechukwudaniel** [comment]
So I can go do it then

**Comment by rin-st** [comment]
hey @Ifechukwudaniel, have you started this? Could you please take challenge 6 https://github.com/scaffold-eth/se-2-challenges/issues/19 instead of this one?

**Comment by Ifechukwudaniel** [comment]
Ok i have already done far

**Comment by Ifechukwudaniel** [comment]
Am working on the draft , i just had a rough week , i should be done by tomorrow

**Comment by Pabl0cks** [comment]
> @Pabl0cks Am working on the draft, i just had a rough week, i should be done by tomorrow

Thx Daniel ♥ Don't want to rush you, if you missing something we can give a hand, no worries!! 🙌

**Comment by Ifechukwudaniel** [comment]
Thanks, if I need anything ask

**Comment by technophile-04** [comment]
We completed the basic / full iteration at #84  🙌
