### ISSUE TITLE
Implement Challenge #6 : 👛 Multisig Wallet Challenge

### ISSUE THREAD

**Issue by Ifechukwudaniel** [scaffold-eth/se-2-challenges#19]
TODO :

- [ ]  Contracts 
- [ ]  UI 
- [ ] Readme 
- [ ] Tests

**Comment by Ifechukwudaniel** [comment]
@carletex  is anyone doing this

**Comment by Pabl0cks** [comment]
Let's finish #15 #18 and  #21 first, since they are the challenges that can be submitted by users, therefore more critical than Challenge 6 and 7 which aren't submitted in [speedrunethereum.com](https://speedrunethereum.com/)

**Comment by Ifechukwudaniel** [comment]
ok

**Comment by Pabl0cks** [comment]
Closing this, merged in #112
