### ISSUE TITLE
No Next.js version could be detected in your project. Make sure `"next"` is installed in "dependencies" or "devDependencies

### ISSUE THREAD

**Issue by anton-karlovskiy** [scaffold-eth/se-2-challenges#193]
I connected the GitHub repo to Vercel (through the Vercel UI) according to https://scaffold-eth-2-docs.vercel.app/deploying/deploy-nextjs-app.
And pushed commits to a challenge branch: `challenge-2-token-vendor`.

I set up domains like this:
![image](https://github.com/user-attachments/assets/cd79610a-0222-4cc2-8fcf-14b89cf4347f)

General settings:
![image](https://github.com/user-attachments/assets/f5f2a6bc-4ef5-4951-8653-caa9f7443327)

Development fails like this:
No Next.js version could be detected in your project. Make sure "next" is installed in "dependencies" or "devDependencies
![Capture](https://github.com/user-attachments/assets/3515bfca-26aa-4e2b-9e7e-75c15cdbe3ae)

Could you please help me find out what I did wrong?
Thank you.

cc @rin-st @technophile-04 @MattPereira

**Comment by technophile-04** [comment]
I am not sure what went wrong, but ideally while connecting repo to vercel it should have auto detected the root dir as `packages/nextjs`

![Screenshot 2024-08-09 at 4 43 09 PM](https://github.com/user-attachments/assets/584354d0-4435-4498-810d-3714c94ef2f2)

Nevertheless you could manually mention in "Root Directory" input with `packages/nextjs`(checkout out your second screen shot the General settings one)

**Comment by anton-karlovskiy** [comment]
@technophile-04 

I have already tried inputting `packages/nextjs` in "Root Directory" and it would not work.
If it should have auto-detected the root dir, I might have done something wrong.

Thank you for your comment.

**Comment by anton-karlovskiy** [comment]
> I am not sure what went wrong, but ideally while connecting repo to vercel it should have auto detected the root dir as `packages/nextjs`
> 
> ![Screenshot 2024-08-09 at 4 43 09 PM](https://private-user-images.githubusercontent.com/80153681/356509443-584354d0-4435-4498-810d-3714c94ef2f2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MzgwNTksIm5iZiI6MTcyNDQzNzc1OSwicGF0aCI6Ii84MDE1MzY4MS8zNTY1MDk0NDMtNTg0MzU0ZDAtNDQzNS00NDk4LTgxMGQtMzcxNGM5NGVmMmYyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDE4MjkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0NDYzYjc2YTAwOWMwYmRjN2VmMDkwYjQyZjM5ODJiZTJmZDdmZWM3NWNmMjE0MTY4OThmOTJjNWM0MDQ0MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wz4Tu2cl3n2Wuz5w2E_0nYXFE4osdFraQk3DlJC11j0)
> 
> Nevertheless you could manually mention in "Root Directory" input with `packages/nextjs`(checkout out your second screen shot the General settings one)

Vercel does not auto-detect the root dir. And even if I manually set it, build fails.
![image](https://github.com/user-attachments/assets/84f691c2-e92c-44b9-bfaa-9a0ca009c450)

**Comment by anton-karlovskiy** [comment]
> I am not sure what went wrong, but ideally while connecting repo to vercel it should have auto detected the root dir as `packages/nextjs`
> 
> ![Screenshot 2024-08-09 at 4 43 09 PM](https://private-user-images.githubusercontent.com/80153681/356509443-584354d0-4435-4498-810d-3714c94ef2f2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MzgwNTksIm5iZiI6MTcyNDQzNzc1OSwicGF0aCI6Ii84MDE1MzY4MS8zNTY1MDk0NDMtNTg0MzU0ZDAtNDQzNS00NDk4LTgxMGQtMzcxNGM5NGVmMmYyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDE4MjkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0NDYzYjc2YTAwOWMwYmRjN2VmMDkwYjQyZjM5ODJiZTJmZDdmZWM3NWNmMjE0MTY4OThmOTJjNWM0MDQ0MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wz4Tu2cl3n2Wuz5w2E_0nYXFE4osdFraQk3DlJC11j0)
> 
> Nevertheless you could manually mention in "Root Directory" input with `packages/nextjs`(checkout out your second screen shot the General settings one)

This is the build result.
![image](https://github.com/user-attachments/assets/ff3fb1c3-045c-43fe-a56a-2ea6c3cf5257)

**Comment by anton-karlovskiy** [comment]
> I am not sure what went wrong, but ideally while connecting repo to vercel it should have auto detected the root dir as `packages/nextjs`
> 
> ![Screenshot 2024-08-09 at 4 43 09 PM](https://private-user-images.githubusercontent.com/80153681/356509443-584354d0-4435-4498-810d-3714c94ef2f2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0Mzg4MzQsIm5iZiI6MTcyNDQzODUzNCwicGF0aCI6Ii84MDE1MzY4MS8zNTY1MDk0NDMtNTg0MzU0ZDAtNDQzNS00NDk4LTgxMGQtMzcxNGM5NGVmMmYyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDE4NDIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhMzExODcxYTJlZDg3NzQ2MDkzNDg5MzBlNmFiNjIyZGFiZWY0NjMzNGJjZTI3ZTkzNmY2NGNhOGJkODVjNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R9eHLX3_U-sXf8aKzEdv2kf30RmiBAwkVTuPoBl4bBU)
> 
> Nevertheless you could manually mention in "Root Directory" input with `packages/nextjs`(checkout out your second screen shot the General settings one)

Do I have to override these commands manually?
![image](https://github.com/user-attachments/assets/c84ef9ae-0ec1-4c0d-b051-3ef4d9ce2f22)

**Comment by technophile-04** [comment]
Hey @anton-karlovskiy, not sure what you are doing wrong. Can you make sure that your github repo default branch on contains code from challenge-2 and you are not deploying the `main` of challenge repo? Since `main` branch of [challenges only have README.md init](https://github.com/scaffold-eth/se-2-challenges). 

So make sure you have correct branch while deploying and it should auto-detect. 

![Screenshot 2024-09-05 at 12 44 37 PM](https://github.com/user-attachments/assets/9ef4b206-d898-4879-84ad-017d93d723e0)


If the above doesn't help could you share the screenshot of what the "source" looks like for you deployment: 

![Screenshot 2024-09-05 at 12 41 35 PM](https://github.com/user-attachments/assets/478dc0ba-057e-4545-b1af-f75a418bc11d)
