### ISSUE TITLE
Frontend link is wrong in challenge#1

### ISSUE THREAD

**Issue by aslikaya** [scaffold-eth/se-2-challenges#204]
In Challenge 1 and checkpoint 5, it is being said to view our frontend at http://localhost:3000/stakerUI and verify the correct network. However Staker UI correct link is: http://localhost:3000/staker-ui

**Comment by rin-st** [comment]
Thanks @aslikaya ! Fixed https://github.com/scaffold-eth/se-2-challenges/commit/ebc345979f2bde456b383d5a99b51a2de92bea8e
