### ISSUE TITLE
Add sepolia alternatives 

### ISSUE THREAD

**Issue by rin-st** [scaffold-eth/se-2-challenges#215]
We have a problem with gas fees on Sepolia and people ask to add support of other testnets.

I think we need to add support for `arbitrumSepolia`, `optimismSepolia`, `polygonAmoy` (`polygonMumbai` is deprecated), and `baseSepolia`.

Steps:
1. Add verification for contracts on these networks. It's required for downloading contracts code, we need it for auto-grader. Upgrade all the challenges. Challenge 0 PR (will be changed to `base-challenge-template` branch and then merged to others): https://github.com/scaffold-eth/se-2-challenges/pull/214
2. Update SRE repo to support new testnets https://github.com/BuidlGuidl/SpeedRunEthereum/pull/209
3. Update auto-grader to support new testnets https://github.com/austintgriffith/speedrun-grader/pull/10

2 and 3 should be merged almost at the same time since APIs are updated. I think I can add backward compatibility if needed, so things won't break between merging 2 and 3

----
To test:
- Start `se-2-challenges` from `verify-testnets` branch https://github.com/scaffold-eth/se-2-challenges/pull/214 . Get your own API key from block explorers or from SRE chat. Deploy to one of the new testnets and verify it. Save link to your contract from block explorer (etherscan etc)
- Run SpeedRunEthereum locally from `more-testnets-support` branch https://github.com/BuidlGuidl/SpeedRunEthereum/pull/209 . My backend `.env` file contained only `AUTOGRADING_SERVER=http://localhost:54727`
- Run auto-grader locally from `more-testnets-support` branch https://github.com/austintgriffith/speedrun-grader/pull/10 . Don't forget to add API keys to `.env`. Run `node install` to update versions of your challenges
- open your local version of SpeedRunEthereum, submit challenge 0 with your saved link. If everything is ok challenge should be submitted in some seconds

----

For now, I created PRs just for discuss, check how it works with challenge 0 and review the code

cc @technophile-04 @Pabl0cks @carletex @damianmarti

**Comment by damianmarti** [comment]
Maybe only adding support for Base Sepolia is enough and we should change the challenge texts to use Base Sepolia instead of Sepolia.

**Comment by technophile-04** [comment]
> Base Sepolia is enough and we should change the challenge texts to use Base Sepolia instead of Sepolia.

Yup I think one testnet makes more sense! 

and base sepolia looks goods to me and we can point people to this page to get sepolia funds: https://docs.base.org/docs/tools/network-faucets/

**Comment by rin-st** [comment]
[added optimism info](https://github.com/scaffold-eth/se-2-challenges/pull/214/files?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) to challenge 0 draft readme. Planning to move it to `base-challenge-template` branch

**Comment by rin-st** [comment]
We added support of OP sepolia
