### ISSUE TITLE
Troubleshooting: yarn account Returning 0 Balance 

### ISSUE THREAD

**Issue by Belloabraham121** [scaffold-eth/se-2-challenges#228]
### Problem  
When using `yarn account` to check the ETH balance of a wallet on the Sepolia network, builders may encounter an issue where the balance always shows as 0, even when the wallet has Sepolia ETH.  

### Root Cause  
This happens because the Hardhat configuration is not set up with a valid custom RPC provider URL due to Alchemy restrictions. Without this, Hardhat cannot connect properly to the Sepolia network, resulting in a balance of 0.

### Suggested Solution  
1. Update the **documentation** to include a troubleshooting note for this scenario.  
2. Add the following note under the relevant section:  

> **Note:** If your balance is 0, configure the Alchemy RPC URL by adding your own custom URL (e.g., using `ALCHEMY_API_KEY`) to the `.env` file. Ensure the `.env` includes the required keys: `DEPLOYER_PRIVATE_KEY=`, `ALCHEMY_API_KEY=`, and `ETHERSCAN_OPTIMISTIC_API_KEY=`.  

Also, confirm that Sepolia ETH has been sent to the address.  

3. Example `.env` configuration:  
   ```dotenv
   DEPLOYER_PRIVATE_KEY=your_private_key
   ALCHEMY_API_KEY=your_alchemy_api_key
   ETHERSCAN_OPTIMISTIC_API_KEY=your_etherscan_optimistic_key
   ```

### Impact  
This change will save builders time and frustration by helping them correctly configure their environment to avoid this issue.

**Comment by Belloabraham121** [comment]
@carletex

**Comment by technophile-04** [comment]
Closing this https://github.com/scaffold-eth/se-2-challenges/pull/229#issuecomment-2497666948
