### ISSUE TITLE
Challenge 1 Iteration Findings

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/se-2-challenges#27]
List of requests/bug findings from running challenge-1-decentralized-staking.  These are not set in stone so feel free to discuss.

**Feature Request** 
Is it possible to default the debug tab to land on the Staker.sol contract upon their initial visit?  

**Feature Request**
This is more of a general SE-2 discussion.  What about moving the Tx pop-up to be below the top tabs?
![image](https://github.com/scaffold-eth/se-2-challenges/assets/12072395/9e1b2d67-ec7c-439c-bb91-e3c211f21b86)

**Feature Request**
We need a more clear complete() process.  Currently all that changes is the total staked on the Staker UI tab as seen in the screenshot.  The old challenge had an atrocious bar that appeared at the top, so let's avoid it being that gross.  Possibly something that appears above the main Staker UI box displaying the amount staked?
![image](https://github.com/scaffold-eth/se-2-challenges/assets/12072395/c8d6009d-f5b3-4462-9965-bc8f04a992cd)

**Comment by technophile-04** [comment]
Tysm @ZakGriffith this are great suggestions 🙌

> Is it possible to default the debug tab to land on the Staker.sol contract upon their initial visit?

Already fixed in #34

> This is more of a general SE-2 discussion. What about moving the Tx pop-up to be below the top tabs?
![Screenshot 2023-07-28 at 4 56 46 AM](https://github.com/scaffold-eth/se-2-challenges/assets/80153681/c1b3e8e4-9907-4056-b1fd-51be2c34d607)

Not sure about this, like in most apps usually they appear from top of the screen that's why it defaults in SE-2 but happy to happy update if others agree 🙌 

> We need a more clear complete() process. Currently, all that changes is the total staked on the Staker UI tab as seen in the screenshot. The old challenge had an atrocious bar that appeared at the top, so let's avoid it being that gross. Possibly something that appears above the main Staker UI box displaying the amount staked?

I didn't completely get it 😅 but are we talking about showing something more visual for the amount staked? something like this maybe? 
![Screenshot 2023-07-28 at 5 06 01 AM](https://github.com/scaffold-eth/se-2-challenges/assets/80153681/c7c85ffc-9dfa-4a92-94f1-eea976cb5708)

**Comment by ZakGriffith** [comment]
> I didn't completely get it 😅 but are we talking about showing something more visual for the amount staked? something like this maybe?

I wasn't very clear with that description 🙃.  In the SE1 version after the threshold is met, the timeleft is 0, and someone calls execute, it calls complete() in the ExampleExternalContract.sol contract and actually stakes the Eth.  Then this huge banner appears at the top(my example says 0 but it would have the real amount)

![image](https://github.com/scaffold-eth/se-2-challenges/assets/12072395/15d12fd3-7306-4d66-b53e-a0bab6814c1e)

This shows the user that since all checks were met the Eth got actually staked.

In the current SE2 version, all that happened is that the total staked here went to 0 with no other way of notifying the user what just happened.

![image](https://github.com/scaffold-eth/se-2-challenges/assets/12072395/11a30377-cd53-4c76-aa46-0e6af3d59933)

I think the users could benefit from something else appearing saying how much was staked.

**Comment by technophile-04** [comment]
> I wasn't very clear with that description 🙃. In the SE1 version after the threshold is met, the timeleft is 0, and someone calls execute, it calls complete() in the ExampleExternalContract.sol contract and actually stakes the Eth. Then this huge banner appears at the top(my example says 0 but it would have the real amount)

Tysm @ZakGriffith for noticing 🙌, I just missed this part in challenge-1 

Updated #34 with something like this : 
![Screenshot 2023-07-31 at 11 49 55 PM](https://github.com/scaffold-eth/se-2-challenges/assets/80153681/1a70b537-a6ef-4bfa-a1e3-4c40cef1b1be)

Please feel free to request for any changes on #34 🙌

**Comment by ZakGriffith** [comment]
That is perfect, nice!!
