### ISSUE TITLE
Challenge 2 - Linting Errors

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/se-2-challenges#35]
index.tsx has a few linting and prettier errors/warnings that cause the yarn vercel command to fail unless ignored.

**Comment by carletex** [comment]
In the base-template, we removed some checks to avoid newcomers having issues with types:

- Removed husky pre-commit hook
- Removed Github action

We decided we wanted to prioritize being friendly to beginners (starting with the challeges and getting block by types/eslint is frustating) over perfect types/eslint. They will have to face types/eslint on SE-2 :) (after the challenges)

**I think we should also remove the check when deploying.**  We'd just need to tweak `next.config.js` and ignoring typescript/eslint by default.

Thoughts? @ZakGriffith @technophile-04 @rin-st ?

**Comment by technophile-04** [comment]
> I think we should also remove the check when deploying

Yup makes sense 🙌

**Comment by rin-st** [comment]
Agree too

**Comment by ZakGriffith** [comment]
Agreed as well

**Comment by ZakGriffith** [comment]
Closing this as PR #39 ignores the linting errors, which allows us to keep the the quotes and apostrophes more readable.
