### ISSUE TITLE
Challenge 2 - Front end error after setting sepolia as targetNetwork

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/se-2-challenges#37]
When setting the targetNetwork in packages/nextjs/scaffold.config.ts to sepolia, I started getting a front end error when clicking into the Token Vendor tab.  When testing on localhost, below is the pop-up error received.

![image](https://github.com/scaffold-eth/se-2-challenges/assets/12072395/86c835a1-99c1-4544-9547-27d56370f17b)

When switching the targetNetwork to hardhat or goerli, there was no pop-up or console errors.

After deploying to vercel an error remained but only in the browser console.  The following is that error.

![image](https://github.com/scaffold-eth/se-2-challenges/assets/12072395/a4e36aeb-ee8b-48f9-b944-23b3db054f06)

I am unsure if this is due to the sepolia RPC acting up or not.

**Comment by rin-st** [comment]
something wrong with sepolia rpc url and cors. Tried challenge 1 and met that error too but se-2 works well. Probably we need to update `wagmi` and it will be solved

**Comment by technophile-04** [comment]
We recently merged #47 and back-merged it in every branch, there was a problem specifically with `sepolia` check out this discussion -> https://github.com/scaffold-eth/scaffold-eth-2/pull/381#issuecomment-1600306689 for more description 

But it should work now. Thanks Zak for mentioning it, closing this, for now, please feel free to reopen it if we still get the error 🙌
