### ISSUE TITLE
Base template README

### ISSUE THREAD

**Issue by carletex** [scaffold-eth/se-2-challenges#4]
While we work on #3 let's update the README with all the things that need to be done when creating new challenges

E.g.
- Edit README from the base data
- Update the MetaHeader title / desc
- thumbnail image
- Create new pages in a certain way (to avoid a lot of conflicts when updating for the base-template)
- ... etc

**Comment by technophile-04** [comment]
#### Just extending to Carlos example, adding some learning from #5 : 
1. Mention about adding Challenge Thumbnail in README (https://github.com/scaffold-eth/se-2-challenges/pull/5#discussion_r1241976959) 

2. Tell about adding Thumbanail image  and small desc to `pages/index.tsx`  (https://github.com/scaffold-eth/se-2-challenges/pull/5#discussion_r1241981399) 

3. Regarding structuring in #5 and in #6, I am trying to follow -> Adding new challenge pages required for challenge in `packages/pages/` and components for that challenge goes in `components/{camelCase(challengeName)}` similarly all the uitls goes in `utils/{camelCase(challengeName)}`

4. We can probably skip this but just mentioning it : 
     1. If people use `useScaffoldEvenHistory` hook tell them to give `hint: fromBlock update` 
     2. The section regarding 3rd party services
