### ISSUE TITLE
Challenge 5 - Render bug when switching tabs

### ISSUE THREAD

**Issue by Pabl0cks** [scaffold-eth/se-2-challenges#45]
When you click an action button and change the web browser tab before letting it update. That fires the transaction but when you go back to the tab, the screen is still the old one. 

In most cases (or all of them) it solves doing a refresh on the web browser tab.

Can check this video:
https://www.loom.com/share/f8a5ad7853534cc7bd2b68372a4e4226?source=embed_watch_on_loom_cta

**Comment by rin-st** [comment]
Does this still work for you? It seems it's fixed in https://github.com/scaffold-eth/se-2-challenges/pull/76

**Comment by Pabl0cks** [comment]
> Does this still work for you? It seems it's fixed in https://github.com/scaffold-eth/se-2-challenges/pull/76

Yees! It is fixed now 🔥🔥 Clossing issue 🙌
