### ISSUE TITLE
Challenge 4 - Required token allowance when depositing.

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/se-2-challenges#55]
Currently when a user is calling deposit, if the ratio of ETH:Balloons isn't 1:1 the amount that needs to be approved is unclear.  I believe this has been solved in the past by just approving a large number to get past it. 

- Is this important enough to include in the challenge, or as it fine as is?

If we want to include it there are a couple options:

1. Build it into the UI to display the required allowance as they enter numbers into the Deposit input field.  I believe the front end should have both the numbers and could calculate quickly without contract interaction.
2. Update the ReadMe to describe how to get the appropriate amount using the price function.

**Comment by Pabl0cks** [comment]
I think we can close this issue, got solved in #61 adding extra info to the Readme
