### ISSUE TITLE
Readme's difference

### ISSUE THREAD

**Issue by rin-st** [scaffold-eth/se-2-challenges#57]
`Deploy it`, `ship it`, `verification`, `flex`?, `next steps` checkpoints differs almost in every challenge's readme. I believe it's better to do it same.

@ZakGriffith , @Pabl0cks , @technophile-04 what do you think?

**Comment by ZakGriffith** [comment]
Great catch.  I'll get on fixing the headers of each checkpoint. (Didn't check the content).  At the bottom is a quick copy/paste to show an overview of the relevant checkpoints just to clear it in my head. 

- [ ] Challenge 1 needs CP4 changed to 💾 Deploy your contract! 🛰 and CP 5 changed to 🚢 Ship your frontend! 🚁
- [ ] Challenge 5 needs CP 1 renamed to something that doesn't say Deployments to avoid confusion.  Configure Guru & Rube maybe?
- [ ] I hate to say it, but Challenge 5 needs more Emoji's in the other checkpoint headers as well 😞

Let me know if I missed any.  Looks like these are already in the base branch, no need to back merge anything.

Challenge 0
Checkpoint 0: 📦 Environment 📚
Checkpoint 3: 💾 Deploy your contract! 🛰
Checkpoint 4: 🚢 Ship your frontend! 🚁
Checkpoint 5: 📜 Contract Verification
Checkpoint 6: 💪 Flex!

Challenge 1
Checkpoint 0: 📦 Environment 📚
Checkpoint 4: 🚢 Ship it 🚁
Checkpoint 5: 🎚 Frontend 🧘‍♀️
Checkpoint 6: 📜 Contract Verification

Challenge 2
Checkpoint 0: 📦 Environment 📚
Checkpoint 4: 💾 Deploy your contracts! 🛰
Checkpoint 5: 🚢 Ship your frontend! 🚁
Checkpoint 6: 📜 Contract Verification

Challenge 4
Checkpoint 0: 📦 Environment 📚
Checkpoint 7: 💾 Deploy your contracts! 🛰
Checkpoint 8: 🚢 Ship your frontend! 🚁
Checkpoint 9: 📜 Contract Verification
Checkpoint 10: 💪 Flex!

Challenge 5
checkpoint 0: 📦 Environment 📚
Checkpoint 6: 💾 Deploy your contracts! 🛰
Checkpoint 7: 🚢 Ship your frontend! 🚁
Checkpoint 8: 📜 Contract Verification

**Comment by ZakGriffith** [comment]
Yolo'd those fixes in.

**Comment by rin-st** [comment]
Thanks @ZakGriffith ! It's much easier to see what's wrong now.

> Let me know if I missed any

- What about `Flex!` checkpoint? Why is it only on Ch 0 and Ch 4?
- There is no "head to your next challenge" block at the end of Ch 4 Readme
- Content differs a little bit, for example, verification in Ch 4. It seems there are small changes in deploy/ship/verify checkpoints of other challenges too. We need to check it, probably add content of that checkpoints to base branch too

**Comment by ZakGriffith** [comment]
> * What about `Flex!` checkpoint? Why is it only on Ch 0 and Ch 4?

The Flex checkpoint is for the challenges that have a cool way to show it off.  I think it works fine in Challenge-0, but think it should probably be removed from Challenge 4.

> * There is no `head to your next challenge` block at the end of Ch 4 Readme

I see it there, did someone yolo it in already?

> * Content differs a little bit, for example, verification in Ch 4. It seems there are small changes in deploy/ship/verify checkpoints of other challenges too. We need to check it, probably add content of that checkpoints to base branch too

Agreed

**Comment by technophile-04** [comment]
> I think it works fine in Challenge-0, but think it should probably be removed from Challenge 4
Lol personally while I was doing SRE and learning solidity doing challenge-4 felt like a great achievement to me so lol that Flex kind of makes sense to me 😂, but we can remove it since there are now addition of other new challenges too 🙌

> here is no head to your next challenge block at the end of Ch 4 Readme
> I see it there, did someone yolo it in already?

Yup, I think its already present there 🙌

---

Went through the challenges to find out the difference and found this( this are relative to challenge-0 since found it "Deploy your contract/frontend" section robust and easy ) : 

- Chall-0

  - [ ] put "Head over to next challenge" in the callout

- Chall-1

  - [ ] "Deploy Your Contract" needs to be updated with images and copy-pastable similar to chall-0
  - [ ] "Ship Your Frontend" needs to be updated with images and copy-pastable commands as well

- Chall-2

  - [ ] "Deploy Your Contract" need images and copy-pastable commands
  - [ ] "Ship Your Frontend" needs copy-pastable commands

- Chall-5
  - [ ] "Deploy Your Contract" need images and copy-pastable commands
  - [ ] "Ship Your Frontend" needs copy-pastable commands

**Comment by ZakGriffith** [comment]
That's very true, there is some inconsistency in the Deploy and Ship checkpoints in the challenges.  I'll dig into that.  

The screenshots and copy/paste commands in challenge 0 are more of a beginner "hand holding" thing.  Once they have gone through that challenge, they (hopefully) don't need that much assistance in the following challenges so I am okay with how those are setup now, with a few tweaks.

**Comment by Pabl0cks** [comment]
Nice job catching those differences and checking all Readmes! Sorry I couldn't check this issue before.

> The screenshots and copy/paste commands in challenge 0 are more of a beginner "hand holding" thing. Once they have gone through that challenge, they (hopefully) don't need that much assistance in the following challenges so I am okay with how those are setup now, with a few tweaks.

Yeah I agree, I think that's nice for chall 0 since most of users will start with that one, but probably after first challenge it's not necesary so much detail. 

Checking passed Challenges data, I think most of us start with Chal 0.
- 2% of users passed Chal 1 and not Chal 0
- 1% of users passed Chal 2 and not Chal 0
- 48% of users passed Chal 0 and not Chal 1

Let me know if some of you are working in a PR and I can help you reviewing or changing Readme's content 🙌

**Comment by rin-st** [comment]
> I see it there, did someone yolo it in already?

> Yup, I think its already present there 🙌

@ZakGriffith , it's you )) https://github.com/scaffold-eth/se-2-challenges/pull/54/files

> Chall-0
> put "Head over to next challenge" in the callout

It's done already

> "Deploy Your Contract" needs to be updated with images and copy-pastable similar to chall-0

I agree that images not needed except challenge 0.

It's strange that `yarn deploy` is copy-pastable, but `yarn generate` and `yarn account` not. For me, it's better to write commands by hand so it will be easier to remember. People will copy-paste it by `ctrl+c` but they at least need to select the text and to press that two buttons 😄 . So I think we have two options:
- make all 3 copyable
- remove copyable for `yarn deploy`
I believe first is better for ch0, second is better for all other challenges

Other than that, challenge 4 deploy section has images from challenge-0 and should be removed.

**Comment by ZakGriffith** [comment]
> Other than that, challenge 4 deploy section has images from challenge-0 and it's better to remove them.

Yolo'ing these now, along with remove the images from the Ship Your Front end section in each challenge except 0.  

> It's strange that `yarn deploy` is copy-pastable, but `yarn generate` and `yarn account` not. For me, it's better to write commands by hand so it will be easier to remember. People will copy-paste it by `ctrl+c` but they at least need to select the text and to press that two buttons 😄 . So I think we have two options:
> 
> * make all 3 copyable
> * remove copyable for `yarn deploy`

Not exactly sure what you mean here.  Are you referring to the Environment checkpoints here?

**Comment by ZakGriffith** [comment]
> Yolo'ing these now, along with remove the images from the Ship Your Front end section in each challenge except 0.

This is done, along with some consistency tweaks to the Ship your Frontend checkpoints.

**Comment by Pabl0cks** [comment]
> This is done, along with some consistency tweaks to the Ship your Frontend checkpoints.

Thanks Zak!! Found a small copy&paste bug in the frontend url from that section, created PRs to solve it, if you see it OK just merge them 🙌

**Comment by ZakGriffith** [comment]
Done!  It looks like the only thing left for discussion in this Issue is this part:  

> It's strange that `yarn deploy` is copy-pastable, but `yarn generate` and `yarn account` not. For me, it's better to write commands by hand so it will be easier to remember. People will copy-paste it by `ctrl+c` but they at least need to select the text and to press that two buttons 😄 . So I think we have two options:
> 
>     * make all 3 copyable
> 
>     * remove copyable for `yarn deploy`

**Comment by rin-st** [comment]
> Not exactly sure what you mean here. Are you referring to the Environment checkpoints here?

It's about deployment checkpoint. But since it's changed for all challenges except ch0, so (very minor) question is just about ch0. 
> It's strange that yarn deploy is copy-pastable, but yarn generate and yarn account not

![image](https://github.com/scaffold-eth/se-2-challenges/assets/25638585/c7efe211-e7fe-4956-8844-65bc63a99d96)

**Comment by ZakGriffith** [comment]
Ahh nice, didn't catch that.  I'm guessing it was initially setup like that since the other commands each had an accompanying screenshot but deploy didn't.  I vote we remove the copy/paste from the deploy line.

🚀 Deploy your NFT smart contract with `yarn deploy`

**Comment by ZakGriffith** [comment]
Merged, thank you!  I believe we have covered everything in this Issue to going to close it.  Feel free to re-open if we didn't clear everything, or create a new one.  Going to take some fresh passes at the ReadMe's again.
