### ISSUE TITLE
Migration to Wagmi V1 and Viem

### ISSUE THREAD

**Issue by technophile-04** [scaffold-eth/se-2-challenges#72]
### Description : 

When we created se-2-challenges repo at that time SE-2 didn't have Wagmi V1 & Viem.

So basically in SE-2 on frontend side we are no more using `ethers` instead we are using [`viem`](https://viem.sh). Also there are some minor api changes. 

As I see people don't focus on the frontend in initial challenges, so it's kind of ok to have it a bit outdated but I think we should start slowly migrating to the latest changes of SE-2 at least till Wagmi V1 & Viem (also in se-2-challenges we are also kind of pushing them toward frontend a bit). 

Because incase of curiosity if people go to [wagmi docs](https://wagmi.sh) they will be seeing V1 docs, also same for [daisyUI docs](https://daisyui.com/)  it will take them to V3 docs and in challenges we are using v2 docs (Not that big deal for daisyUI). 

Regarding MultiSig Challenge #19  and SVG NFT #20  challenge I think these challenges must for sure use the latest SE-2 changes at least with Wagmi v1, viem, and daisui V3 because at this challenges people start understanding/exploring the scaffold-eth frontend more. 

```[tasklist]
### Tasks
- [x] Migrate base template to wagmi v1, Viem and DaisyUI v3
- [x] Migrate Challenge 0
- [x] Migrate challenge 1
- [x] Migrate challenge 2
- [x] Migrate challenge 3
- [x] Migrate challenge 4
- [x] Migrate challenge 5
```

**Comment by rin-st** [comment]
@mertcanciy hey, do you want to take challenge 4?
