### ISSUE TITLE
Challenge 0: use different package instead of react-json-view

### ISSUE THREAD

**Issue by technophile-04** [scaffold-eth/se-2-challenges#90]
### Description : 

It seems that the package we are using to show IPFS upload JSON data on UI seems not be maintained anymore and has some problem with SSR 

We got away with the issue of SSR by using `next/dynamic` import: 
https://github.com/scaffold-eth/se-2-challenges/blob/a84c35ae8d01e3d081fbec184a932cfd7e1033b7/packages/nextjs/pages/ipfsUpload.tsx#L9

As it was suggested here -> https://github.com/mac-s-g/react-json-view/issues/121#issuecomment-437267883

But it seems that in the latest very next version it breaks #89 

Alternative which I found : https://viewer.textea.io/ but tells you to add `@mui/material @emotion/react @emotion/styled` as dependencies :( don't know if its worth it

**Comment by rin-st** [comment]
Hey Shiv, 
`use client` + [React.lazy](https://github.com/scaffold-eth/se-2-challenges/blob/challenge-0-simple-nft/packages/nextjs/app/ipfsDownload/page.tsx#L8) fixed the problem.

can I close this issue?

**Comment by rin-st** [comment]
Closing this for now, since SSR problem is fixed, and `react-json-view` is still popular and enough for us. Will reopen later if needed
