### ISSUE TITLE
Challenge 1 Checkpoint 1: Staking - "Stake Events" table data not loading

### ISSUE THREAD

**Issue by tantodefi** [scaffold-eth/se-2-challenges#92]
the data in `Stake Events` tab isn't loading correctly after making some  staking transactions and I'm not finding any helpful errors in dev console

Any ideas on this?

https://decentralized-staking-coral.vercel.app/stakings

![Screenshot](https://github.com/scaffold-eth/se-2-challenges/assets/107724252/a2542e6c-6581-4735-bdc1-6262977131a5)

**Comment by rin-st** [comment]
Is it working for you locally?
I see only one Stake event on your account, is it worked before and stopped?

**Comment by tantodefi** [comment]
i took a look at your PR and tried it with both the named and unnamed `Stake` event parameters in my contract and even tried updating the `stakings.tsx` template with the array indexes and it still wasnt working... both on my local repo and i tried spinning up a fresh repo to test it and still didn't work for me.

**Comment by rin-st** [comment]
It works for me without named params in solidity contract event and at the same time with array indexes on your tsx file. Have you tried exactly this case?

try to console.log(stakeEvents) in your `stakings.tsx`. What does it show to you? What's inside `args` prop of events?

**Comment by tantodefi** [comment]
It worked! 

https://decentralized-staking-h42nz6owu-tantodefi.vercel.app/stakings

my bad I missed updating one of the array index values 

Thanks so much @rin-st
